CLASS ztest_nico_abap_git DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    DATA: ls_table TYPE ZOMER_ULUCAN-test2.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ztest_nico_abap_git IMPLEMENTATION.
ENDCLASS.
